title: INFORMATICA MUSICALE PER IL CONSERVATORIO S. CECILIA DI ROMA

email: me@giuseppesilvi.com

description: > # IMCSC

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username:

github_username:  grammaton

google_analytics:

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

info:
  name: "Giuseppe Silvi"
